---
name: scripts-demo
bundle_prefix:
  - ycappuccino.storage
  - ycappuccino.endpoints_service
  - ycappuccino.scripts
  - library
layers:
  ycappuccino_storage_memory:
    active: true
config:
  http_server:
    active: false
